[package]
name = "VolatusOracle"
version = "1.0.0"
authors = []

[addresses]
volatus_oracle = "0x3bf7a7aaaaf14e5f30d566d7bb2e5493f5f8f046e56d6b574ea3d9d99849fe79"
pyth = "0x9357e76fe965c9956a76181ee49f66d51b7f9c3800182a944ed96be86301e49f"
deployer = "0xa3ad2d9c8114b9a4fe97d45b7a9d3c731148d936b0f5dd396fc20a53a11a70da"
wormhole = "0x9236893d6444b208b7e0b3e8d4be4ace90b6d17817ab7d1584e46a33ef5c50c9"

[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dependencies.Pyth]
git = "https://github.com/pyth-network/pyth-crosschain.git"
rev = "mainnet"
subdir = "target_chains/aptos/contracts"

[dev-dependencies]
